# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target ‘XMPP’ do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  #pod install --verbose --no-repo-update（跳过更新进行安装）
  #pod update --verbose --no-repo-update（跳过更新进行更新）
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'JSONModel', '~> 1.7.0'
  pod 'FMDB', '~> 2.6.2'
  pod 'CocoaAsyncSocket', '~> 7.4.1'
  pod 'Masonry', '~> 1.0.2'
  pod 'SDWebImage', '~> 4.0.0-beta2'
#  pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'

 
end

